name: NMSAssistant
module: skills.nms_assistant.main
description:
  en: This skill fetches information about No Man's Sky items, elements, crafting, cooking, expeditions, community missions, game news, and patch notes.
  de: Dieser Skill ruft Informationen über No Man's Sky-Artikel, Elemente, Handwerk, Kochen, Expeditionen, Gemeinschaftsmissionen, Spielemeldungen und Patch-Notizen ab.
hint:
  en: Use this skill to get detailed information about various aspects of No Man's Sky.
  de: Verwende diesen Skill, um detaillierte Informationen zu verschiedenen Aspekten von No Man's Sky zu erhalten.
examples:
  - question:
      en: What are the latest patch notes?
      de: Was sind die neuesten Patch-Notizen?
    answer:
      en: (fetches and displays the latest patch notes from the game)
      de: (ruft die neuesten Patch-Notizen aus dem Spiel ab und zeigt sie an)
prompt: |
  You are an assistant for No Man's Sky players. You can fetch information about items, elements, crafting, cooking, expeditions, community missions, and game news.
  Use the relevant APIs to provide detailed information requested by the user.
